<?php
  // service information
  $GLOBALS["service_name"] = "ServerBuilder";
  $GLOBALS["service_version"] = "v0.9 Beta";

  // debug mode
  $GLOBALS["debug_mode"] = true;

  // paths
  $GLOBALS["basePath"] = "/var/www/serverbuilder";

  // predefined cvars - array of all cvars the web interface is allowed to set
  $GLOBALS["cvars"] = array(
    "sv_hostname",
    "qlx_serverBrandName",
    "roundtimelimit",
    "qlx_workshopReferences",
    "sv_tags",
    "g_password",
    "bot_enable",
    "bot_autoManage",
    "timelimit",
    "fraglimit",
    "g_instaGib",
    "capturelimit",
    "qlx_infiniteAmmo",
    "g_inactivity",
  );

  // predefined plugins - array of all plugins the web interface is allowed to load
  $GLOBALS["plugins"] = array(
    "botmanager",
    "names",
    "clan",
    "plugin_manager",
    "balance",
    "custom_votes",
    "fun",
    "tp_fun",
    "aliases",
  );

  // game factories
  $GLOBALS["factories"] = array(
    "ad" => "Attack and Defend",
    "ca" => "Clan Arena",
    "ctf" => "Capture The Flag",
    "dom" => "Domination",
    "duel" => "Duel",
    "oneflag" => "1-Flag CTF",
    "ffa" => "Free For All",
    "ft" => "Freeze Tag",
    "har" => "Harvester",
    "ictf" => "Instagib CTF",
    "iffa" => "Instagib FFA",
    "ift" => "Instagib Freeze Tag",
    "infected" => "Infected",
    "quadhog" => "Quad Hog",
    "race" => "Race",
    "rr" => "Red Rover",
    "tdm" => "Team Deathmatch",
    "vca" => "Vampiric CA",
  );

  // game weaponry
  $GLOBALS["weapons"] = array(
    "1" => "Gauntlet",
    "2" => "Machinegun",
    "4" => "Shotgun",
    "8" => "Grenade Launcher",
    "16" => "Rocket Launcher",
    "32" => "Lightning Gun",
    "64" => "Railgun",
    "128" => "Plasmagun",
    "256" => "BFG-10K",
    "512" => "Grappling Hook",
    "1024" => "Nailgun",
    "2048" => "Prox Launcher",
    "4096" => "Chaingun",
    "8192" => "Heavy Machinegun",
  );

  // vote flags
  $GLOBALS["voteflags"] = array(
    "1" => "Map",
    "2" => "Map Restart",
    "4" => "Next Map",
    "8" => "Factory Change",
    "16" => "Kick",
    "32" => "Timelimit",
    "64" => "Fraglimit",
    "128" => "Shuffle",
    "256" => "Teamsize",
    "512" => "Cointoss/Random Number",
    "1024" => "Loadouts",
    "2048" => "End-Game Map Selection",
    "4096" => "Global/Weapon Ammo Boxes",
    "8192" => "Item Timers",
    "16384" => "Weapon Respawn Times",
  );

  // game maps
  $GLOBALS["maps"] = array(
    "aerowalk" => "Aerowalk",
    "almostlost" => "Almost Lost",
    "arcanecitadel" => "Arcane Citadel",
    "arkinholm" => "Arkinholm",
    "asylum" => "Asylum",
    "basesiege" => "Base Siege",
    "battleforged" => "Battleforged",
    "beyondreality" => "Beyond Reality",
    "bitterembrace" => "Bitter Embrace",
    "blackcathedral" => "Black Cathedral",
    "bloodlust" => "Blood Lust",
    "bloodrun" => "Blood Run",
    "brimstoneabbey" => "Brimstone Abbey",
    "campercrossings" => "Camper Crossings",
    "campgrounds" => "Campgrounds",
    "cannedheat" => "Canned Heat",
    "castledeathstalker" => "Castle Deathstalker",
    "chemicalreaction" => "Chemical Reaction",
    "citycrossings" => "City Crossings",
    "cliffside" => "Cliffside",
    "coldcathode" => "Cold Cathode",
    "coldwar" => "Cold War",
    "concretepalace" => "Concrete Palace",
    "corrosion" => "Corrosion",
    "courtyard" => "Courtyard",
    "cure" => "Cure",
    "cursed" => "Cursed",
    "deadandgone" => "Dead and Gone",
    "deathorglory" => "Death or Glory",
    "deepinside" => "Deep Inside",
    "delirium" => "Delirium",
    "demonkeep" => "Demon Keep",
    "devilish" => "Devilish",
    "diesirae" => "Diesirae",
    "dismemberment" => "Dismemberment",
    "dividedcrossings" => "Divided Crossings",
    "divineintermission" => "Divine Intermission",
    "doubleimpact" => "Double Impact",
    "dreadfulplace" => "Dreadful Place",
    "dredwerkz" => "Dredwerkz",
    "drunkenmummy" => "Drunken Mummy",
    "duelingkeeps" => "Dueling Keeps",
    "elder" => "Elder",
    "electrichead" => "Electric Head",
    "electrocution" => "Electrocution",
    "eviscerated" => "Eviscerated",
    "evolution" => "Evolution",
    "eyetoeye" => "Eye to Eye",
    "falloutbunker" => "Fallout Bunker",
    "fatalinstinct" => "Fatal Instinct",
    "finnegans" => "Finnegan's",
    "fluorescent" => "Fluorescent",
    "foolishlegacy" => "Foolish Legacy",
    "furiousheights" => "Furious Heights",
    "fuse" => "Fuse",
    "futurecrossings" => "Future Crossings",
    "gospelcrossings" => "Gospel Crossings",
    "gothicrage" => "Gothic Rage",
    "grimdungeons" => "Grim Dungeons",
    "hearth" => "Hearth",
    "hektik" => "Hektik",
    "hellsgate" => "Hell's Gate",
    "henhouse" => "Hen House",
    "heroskeep" => "Hero's Keep",
    "hiddenfortress" => "Hidden Fortress",
    "houseofdecay" => "House of Decay",
    "industrialrevolution" => "Industrial Revolution",
    "infinity" => "Infinity",
    "innersanctums" => "Inner Sanctums",
    "intervention" => "Intervention",
    "ironworks" => "Ironworks",
    "japanesecastles" => "Japanese Castles",
    "jumpwerkz" => "Jumpwerkz",
    "leftbehind" => "Left Behind",
    "leviathan" => "Leviathan",
    "limbus" => "Limbus",
    "longestyard" => "Longest Yard",
    "lostparadise" => "Lost Paradise",
    "lostworld" => "Lost World",
    "mcsarges" => "McSarge's",
    "midlifecrisis" => "Midlife Crisis",
    "monastery" => "Monastery",
    "namelessplace" => "Nameless Place",
    "newcerberon" => "New Cerberon",
    "overgrowth" => "Overgrowth",
    "overkill" => "Overkill",
    "overlord" => "Overlord",
    "phrantic" => "Phrantic",
    "pillbox" => "Pillbox",
    "provinggrounds" => "Proving Grounds",
    "pulpfriction" => "Pulp Friction",
    "purgatory" => "Purgatory",
    "quarantine" => "Quarantine",
    "qzpractice1" => "Elevate",
    "qzpractice2" => "Accelerate",
    "qztraining" => "Training",
    "ragnarok" => "Ragnarok",
    "railyard" => "Railyard",
    "realmofsteelrats" => "Realm of Steel Rats",
    "rebound" => "Rebound",
    "refinery" => "Refinery",
    "reflux" => "Reflux",
    "repent" => "Repent",
    "retribution" => "Retribution",
    "revolver" => "Revolver",
    "satanic" => "Satanic",
    "scornforge" => "Scornforge",
    "seamsandbolts" => "Seams and Bolts",
    "servitude" => "Servitude",
    "shakennotstirred" => "Shaken not Stirred",
    "shiningforces" => "Shining Forces",
    "siberia" => "Siberia",
    "silence" => "Silence",
    "sinister" => "Sinister",
    "skyward" => "Skyward",
    "smash" => "Smash",
    "solarium" => "Solarium",
    "solid" => "Solid",
    "somewhatdamaged" => "Somewhat Damaged",
    "sorrow" => "Sorrow",
    "spacechamber" => "Space Chamber",
    "spacectf" => "Space CTF",
    "spidercrossings" => "Spider Crossings",
    "spillway" => "Spillway",
    "stonekeep" => "Stonekeep",
    "stronghold" => "Stronghold",
    "terminalheights" => "Terminal Heights",
    "terminatria" => "Terminatria",
    "terminus" => "Terminus",
    "theatreofpain" => "Theatre of Pain",
    "thedukesgarden" => "The Duke's Garden",
    "theedge" => "The Edge",
    "theepicenter" => "The Epicenter",
    "theoldendomain" => "The Olden Domain",
    "threestory" => "Three Story",
    "thunderstruck" => "Thunderstruck",
    "tornado" => "Tornado",
    "toxicity" => "Toxicity",
    "trinity" => "Trinity",
    "troubledwaters" => "Troubled Waters",
    "useandabuse" => "Use and Abuse",
    "verticalvengeance" => "Vertical Vengeance",
    "vortexportal" => "Vortex Portal",
    "warehouse" => "Warehouse",
    "wargrounds" => "Wargrounds",
    "wicked" => "Wicked",
    "windowpain" => "Window Pain",
    "windsongkeep" => "Windsong Keep",
    "zen" => "Zen",
  );

  // number of servers per location (including 0)
  $GLOBALS["numservers"] = 11;

  // base port
  $GLOBALS["basePort"] = 60000;

  // locations
  $GLOBALS["locations"] = array(
    "Sydney",
    "Adelaide",
  );

  // renderer globals
  $GLOBALS["rendererVars"] = array(
    "service_version" => $GLOBALS["service_version"],
    "service_name" => $GLOBALS["service_name"],
    "locations" => $GLOBALS["locations"],
    "plugins" => $GLOBALS["plugins"],
    "factories" => $GLOBALS["factories"],
    "maps" => $GLOBALS["maps"],
    "weapons" => $GLOBALS["weapons"],
    "voteflags" => $GLOBALS["voteflags"],
  );
